### ISSUE TITLE
Impossible to run the examples

### ISSUE THREAD

**Issue by tomlecoz** [jbaicoianu/threecap#1]
Hello ! 

This project looks great but unfortunately it doesn't work anymore. 
When I try to launch the example, I get 

"Uncaught TypeError: pass.setSize is not a function
    at THREE.EffectComposer.addPass (EffectComposer.js:66)
    at threecap.js:174"

I looked at the code but I didn't find what's wrong (I never used EffectComposer until now)

I hope it's easy to fix 

Thank you for reading and for sharing your work

**Comment by meo1** [comment]
I have the same problem.

**Comment by jbaicoianu** [comment]
Pretty slow turnaround, but this error should be fixed now, thanks @meo1 - I haven't used this library myself in a few years though, so I can't say if this was the only issue.  I'd expect there may be some changes needed to work with the latest threejs, as this was written somewhere around r80

It's probably also worth seeing how well this works with the latest versions of ffmpeg.js which use WASM features and optimizations which weren't available back in 2015.
